//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSalon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManPost()
        {
            this.Record = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Data { get; set; }
        public int Genger { get; set; }
        public int Pol { get; set; }
    
        public virtual POl POl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
    }
}
