//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSalon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManPost
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Data { get; set; }
        public int Genger { get; set; }
        public int Pol { get; set; }
    
        public virtual POl POl1 { get; set; }
    }
}
