//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopSalon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Beloborodov_BarbershopEntities1 : DbContext
    {
        public Beloborodov_BarbershopEntities1()
            : base("name=Beloborodov_BarbershopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barber> Barber { get; set; }
        public virtual DbSet<ManPost> ManPost { get; set; }
        public virtual DbSet<Ochered> Ochered { get; set; }
        public virtual DbSet<POl> POl { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
